apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: tenant-b
spec:
  replicas: 3  # Mantendo 3 réplicas para gerar mais tráfego
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      runtimeClassName: kata  # Usando Kata Containers para isolamento adicional
      containers:
      - name: traffic-generator
        image: curlimages/curl:latest
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 600m
            memory: 512Mi
        command:
        - "/bin/sh"
        - "-c"
        - |
          echo "Iniciando gerador de tráfego agressivo para traffic-server..."
          
          # Espera o servidor estar pronto
          echo "Aguardando o traffic-server inicializar..."
          until curl -s --head --fail http://traffic-server; do
            echo "Servidor não está pronto ainda. Aguardando..."
            sleep 5
          done
          
          echo "Servidor disponível! Iniciando geração de tráfego intensivo..."
          
          # Loop infinito gerando tráfego de rede intensivo
          while true; do
            # Baixa arquivos grandes em paralelo
            echo "Baixando múltiplos arquivos grandes (100MB) simultaneamente..."
            for i in $(seq 1 3); do
              curl -s -o /dev/null http://traffic-server/large/100mb.bin &
            done
            
            echo "Gerando carga com múltiplas requisições concorrentes de arquivos médios..."
            for i in $(seq 1 10); do
              curl -s -o /dev/null http://traffic-server/large/10mb.bin &
            done
            
            # Aguarda todos os processos em background terminarem
            wait
            
            echo "Gerando múltiplas requisições pequenas em curto intervalo..."
            for i in $(seq 1 50); do
              curl -s -o /dev/null http://traffic-server/ &
              if [ $((i % 10)) -eq 0 ]; then
                sleep 0.1  # Pequena pausa a cada 10 requisições
              fi
            done
            
            # Aguarda todos os processos em background terminarem
            wait
            
            # Breve pausa antes de iniciar o próximo ciclo
            sleep 2
          done
