Vagrant.configure("2") do |config|
    (1..1).each do |i|
        config.vm.define "master-#{i}" do |k8s|
            k8s.vm.box = "almalinux/8"
            k8s.vm.hostname = "master-#{i}"
            k8s.vm.network "private_network", ip: "172.89.0.1#{i}"

            k8s.ssh.insert_key = false
            k8s.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_ed25519']
            k8s.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/authorized_keys"

            k8s.vm.provider "virtualbox" do |vb|
              vb.gui = false
              vb.cpus = 4
              vb.memory = "8192"  
              vb.customize ["modifyvm", :id, "--cpus", "4"]
            end
        end
    end
end
