apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kata-containers-monitor
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kata-metrics
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: metrics
      interval: 15s
