apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-servicemonitor
  namespace: ingress-nginx
  labels:
    release: prometheus
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  namespaceSelector:
    matchNames:
      - ingress-nginx
  endpoints:
    - port: metrics
      interval: 5s
      scrapeTimeout: 4s
      path: /metrics
      scheme: http