apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tenant-d
  namespace: monitoring
  labels:
    release: prometheus
spec:
  jobLabel: tenant-d
  selector:
    matchLabels:
      app: postgres
  namespaceSelector:
    matchNames:
    - tenant-d
  endpoints:
  - port: postgres
    interval: 15s
    path: /metrics
    scheme: http
    scrapeTimeout: 10s