{
 "title": "Kubernetes / Noisy Lab",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Resources by Namespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=~\"tenant-a|tenant-b|tenant-c\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by (namespace)(container_memory_working_set_bytes{namespace=~\"tenant-a|tenant-b|tenant-c\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttling per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_cpu_cfs_throttled_periods_total{namespace=~\"tenant-a|tenant-b|tenant-c\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttling ratio per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_cpu_cfs_throttled_periods_total{namespace=~\"tenant-a|tenant-b|tenant-c\"}[1m])) / sum by (namespace) (rate(container_cpu_cfs_periods_total{namespace=~\"tenant-a|tenant-b|tenant-c\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Received bytes per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_network_receive_bytes_total{namespace=~\"tenant-a|tenant-b|tenant-c\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Received bytes per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_network_transmit_bytes_total{namespace=~\"tenant-a|tenant-b|tenant-c\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Correlations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CPU Throttling vs. Noisy Tenant CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"tenant-b\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace) (rate(container_cpu_cfs_throttled_periods_total{namespace=\"tenant-a\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace) (rate(container_cpu_cfs_throttled_periods_total{namespace=\"tenant-c\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOMKills vs. Noisy Tenants",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace) (container_memory_working_set_bytes{namespace=\"tenant-b\"} / 1e9)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (namespace) (kube_pod_container_status_last_terminated_reason{namespace=\"tenant-a\", reason=\"OOMKilled\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (namespace) (kube_pod_container_status_last_terminated_reason{namespace=\"tenant-c\", reason=\"OOMKilled\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}