apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-client
  namespace: tenant-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-client
  template:
    metadata:
      labels:
        app: iperf-client
    spec:
      containers:
      - name: iperf3
        image: networkstatic/iperf3
        resources:
          requests:
            cpu: "0.2"
            memory: "128Mi"
          limits:
            cpu: "0.5"
            memory: "256Mi"
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            iperf3 -c iperf-server.tenant-a.svc.cluster.local -t 30
            sleep 10
          done