apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng
  namespace: tenant-b
spec:
  replicas: 2  # Aumentando para 2 réplicas para gerar mais carga
  selector:
    matchLabels:
      app: stress-ng
  template:
    metadata:
      labels:
        app: stress-ng
    spec:
      containers:
      - name: stress-ng
        image: colinianking/stress-ng:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Iniciando stress-ng com timeout de ${ATTACK_DURATION} segundos"
          stress-ng --cpu 4 --vm 2 --vm-bytes 1536M --io 2 --timeout ${ATTACK_DURATION}s --metrics-brief
        env:
        - name: ATTACK_DURATION
          value: "360"  # Será substituído pelo script principal
        resources:
          requests:
            cpu: 800m        # Aumentando solicitação de CPU
            memory: 1Gi      # Aumentando solicitação de memória
          limits:
            cpu: 2           # Aumentando limite de CPU
            memory: 3Gi      # Aumentando limite de memória
        livenessProbe:
          exec:
            command:
            - stress-ng
            - --version
          initialDelaySeconds: 5
          periodSeconds: 20
        readinessProbe:
          exec:
            command:
            - stress-ng
            - --version
          initialDelaySeconds: 5
          periodSeconds: 20