apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: tenant-b
spec:
  replicas: 3  # Aumentando para 3 réplicas para gerar mais tráfego
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
      - name: traffic-generator
        image: curlimages/curl:latest
        resources:
          requests:
            cpu: 300m      # Aumentando request de CPU
            memory: 256Mi  # Aumentando request de memória
          limits:
            cpu: 600m      # Aumentando limite de CPU
            memory: 512Mi  # Aumentando limite de memória
        command:
        - "/bin/sh"
        - "-c"
        - |
          echo "Iniciando gerador de tráfego agressivo para traffic-server..."
          
          # Espera o servidor estar pronto
          echo "Aguardando o traffic-server inicializar..."
          until curl -s --head --fail http://traffic-server; do
            echo "Servidor não está pronto ainda. Aguardando..."
            sleep 5
          done
          
          echo "Servidor disponível! Iniciando geração de tráfego intensivo..."
          
          # Loop infinito gerando tráfego de rede intensivo
          while true; do
            # Baixa arquivos grandes em paralelo
            echo "Baixando múltiplos arquivos grandes (100MB) simultaneamente..."
            for i in $(seq 1 3); do
              curl -s -o /dev/null http://traffic-server/large/100mb.bin &
            done
            
            echo "Gerando carga com múltiplas requisições concorrentes de arquivos médios..."
            for i in $(seq 1 10); do
              curl -s -o /dev/null http://traffic-server/large/10mb.bin &
            done
            
            echo "Iniciando rajada de requisições pequenas..."
            for i in $(seq 1 50); do
              curl -s -o /dev/null http://traffic-server/large/1mb.bin &
            done
            
            # Pequena pausa para evitar que o pod seja morto
            sleep 1
            
            # Gerar tensão na rede com requisições rápidas em sequência
            echo "Gerando rajadas de requisições em sequência..."
            for i in $(seq 1 100); do
              curl -s -o /dev/null http://traffic-server/ &
              if [ $((i % 20)) -eq 0 ]; then
                sleep 0.5
              fi
            done
            
            # Incluir uma pequena pausa para evitar que o pod seja morto por uso excessivo
            sleep 2
          done