apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: tenant-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 400m
            memory: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-benchmark
  namespace: tenant-c
spec:
  template:
    spec:
      containers:
      - name: redis-benchmark
        image: redis:6.2
        command: ["redis-benchmark"]
        args:
        - "-h"
        - "redis-deployment.tenant-c.svc.cluster.local"
        - "-p"
        - "6379"
        - "-c"
        - "50"
        - "-n"
        - "100000"
      restartPolicy: Never
  backoffLimit: 4