apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-stress
  namespace: tenant-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-stress
  template:
    metadata:
      labels:
        app: memory-stress
    spec:
      containers:
      - name: stress-ng
        image: colinianking/stress-ng
        resources:
          requests:
            cpu: "0.1"
            memory: "256Mi"
          limits:
            cpu: "0.2"
            memory: "512Mi"
        command: ["stress-ng"]
        args: ["--vm", "1", "--vm-bytes", "384M", "--vm-hang", "0", "--timeout", "0h"]