apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress
  namespace: tenant-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: stress-ng
        image: colinianking/stress-ng
        resources:
          requests:
            cpu: "0.5"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
        command: ["stress-ng"]
        args: ["--cpu", "1", "--cpu-load", "80", "--timeout", "0h"]